{
 "title": "dashboard_prueba_62d92158",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "LoRa RSSI (dB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "query": "from(bucket: \"allora-bucket\")\r\n  |> range(start: -15m)\r\n  |> filter(fn: (r) => r.mqtt_topic == \"allora/gateway_01/62d92158/metrics\")\r\n  |> filter(fn: (r) => r._field == \"rssi\")\r\n  |> aggregateWindow(every: 10s, fn: last, createEmpty: false)\r\n  |> yield(name: \"RSSI_series\")"
    }
   ]
  },
  {
   "title": "LoRa SNR (dB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "query": "from(bucket: \"allora-bucket\")\r\n  |> range(start: -15m)\r\n  |> filter(fn: (r) => r.mqtt_topic == \"allora/gateway_01/62d92158/metrics\")\r\n  |> filter(fn: (r) => r._field == \"snr\")\r\n  |> aggregateWindow(every: 10s, fn: last, createEmpty: false)\r\n  |> yield(name: \"SNR_series\")"
    }
   ]
  },
  {
   "title": "Internal Temperature (°C)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "import \"internal/debug\"\r\n\r\nbase =\r\n    from(bucket: \"allora-bucket\")\r\n        |> range(start: -15m)\r\n        |> filter(fn: (r) => r.mqtt_topic == \"allora/gateway_01/62d92158/metrics\")\r\n        |> filter(fn: (r) => r._field == \"Temperature\")\r\n        |> aggregateWindow(every: 10s, fn: mean, createEmpty: false)\r\nline =\r\n    base\r\n        |> map(fn: (r) => ({\r\n            r with\r\n            _field: \"BASE\",\r\n        }))\r\n\r\nok =\r\n    base\r\n        |> map(fn: (r) => ({\r\n            r with\r\n            _field: \"OK\",\r\n            _value: if r._value < 40.0 then r._value else debug.null(type: \"float\"),\r\n        }))\r\n\r\nwarn =\r\n    base\r\n        |> map(fn: (r) => ({\r\n            r with\r\n            _field: \"WARN\",\r\n            _value: if r._value >= 40.0 and r._value < 60.0 then r._value else debug.null(type: \"float\"),\r\n        }))\r\n\r\nalarm =\r\n    base\r\n        |> map(fn: (r) => ({\r\n            r with\r\n            _field: \"ALARM\",\r\n            _value: if r._value >= 60.0 then r._value else debug.null(type: \"float\"),\r\n        }))\r\n\r\nunion(tables: [line, ok, warn, alarm])\r\n    |> yield(name: \"Temperature_bands\")"
    }
   ]
  },
  {
   "title": "RAM (B)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"allora-bucket\")\r\n  |> range(start: -15m)\r\n  |> filter(fn: (r) => r.mqtt_topic == \"allora/gateway_01/62d92158/metrics\")\r\n  |> filter(fn: (r) => r._field == \"RAM_Total\" or r._field == \"RAM_Usada\" or r._field == \"RAM_Libre\")\r\n  |> group(columns: [\"_field\"])\r\n  |> aggregateWindow(every: 10s, fn: mean, createEmpty: false)\r\n  |> yield(name: \"ram_series\")"
    }
   ]
  },
  {
   "title": "Uptime (s)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"allora-bucket\")\r\n  |> range(start: -30m)\r\n  |> filter(fn: (r) => r.mqtt_topic == \"allora/gateway_01/62d92158/metrics\")\r\n  |> filter(fn: (r) => r._field == \"Uptime\")\r\n  |> aggregateWindow(every: 1s, fn: last, createEmpty: false)\r\n  |> yield(name: \"uptime\")\r\n"
    }
   ]
  },
  {
   "title": "Uptime (hh:mm:ss)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"allora-bucket\")\r\n  |> range(start: -30m)\r\n  |> filter(fn: (r) => r.mqtt_topic == \"allora/gateway_01/62d92158/metrics\")\r\n  |> filter(fn: (r) => r._field == \"Uptime\")\r\n  |> aggregateWindow(every: 1s, fn: last, createEmpty: false)\r\n  |> yield(name: \"uptime\")\r\n"
    }
   ]
  },
  { "title": "Request CONN-ACK", "type": "geeksrus-mqtt-panel", "gridPos": { "h": 3, "w": 3, "x": 3, "y": 20 } },
  { "title": "Soft-Reset Node", "type": "geeksrus-mqtt-panel", "gridPos": { "h": 3, "w": 3, "x": 6, "y": 20 } },
  { "title": "Hard-Reset Node", "type": "geeksrus-mqtt-panel", "gridPos": { "h": 3, "w": 3, "x": 9, "y": 20 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"allora-bucket\")\n  |> range(start: -15m)\n  |> filter(fn: (r) => r.mqtt_topic == \"allora/gateway_01/62d92158/status\")\n  |> filter(fn: (r) => r._field == \"state\")\n  |> last()"
    }
   ]
  }
 ]
}