[agent]
  interval = "5s"
  flush_interval = "5s"

[[inputs.mqtt_consumer]]
  servers = ["tcp://mosquitto:1883"]
  topics = [
    "allora/+/+/metrics",
    "allora/+/+/status"
  ]
  topic_tag = "mqtt_topic"
  data_format = "json"
  json_string_fields = ["state", "message", "command_type"]
  name_override = "node_metrics"
  tagexclude = ["host"]

[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "8Ise_OEimp0bRojsHAuhP3E5V_wNracyv5VsonnrsQ3ifudxqyHvZpP8dsG7jh3yDlaIogZ-39jPEC83mEhRpg=="
  organization = "allora-org"
  bucket = "allora-bucket"